apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: graphqlengine.ssnc-corp.cloud
  - http:
      paths:
      - path: /hasura
        backend:
          serviceName: grapqhl-service
          servicePort: 3200


        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
          name: myingress
          labels:
              name: myingress
        spec:
          rules:
          - host: <Host>
            http:
              paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    serviceName: <Service>
                    servicePort: <Port>
        