apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default

spec:
  rules:
  - host: graphqlengine.ssnc-corp.cloud
  - http:
      paths:
      - path: /graphql
        backend:
          serviceName: grapqhl-service
          servicePort: 3200
      - path: /minio
        backend:
          serviceName: minio-service 
          servicePort: 5000
          