apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
spec:
  storageClassName: nfs-managed-storage
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
