apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-managed-storage
  nfs:
    path: "/nfsshare"
    server: "10-234-52-22.ssnc-corp.cloud"
    readOnly: false
