apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    info: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: DATABASE_USER
                name: database-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: postgres

        ports:
        - containerPort: 5432
          name: postgres-db
        volumeMounts:
        - name: nfs-storage
          mountPath: /nfs-storage
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
          #      volumes:
          #- name: pv-data
          #          persistentVolumeClaim:
                  #   claimName: postgresvolume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
#  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 4200
    targetPort: 5432
