apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pure-block
  #  namespace: minio-storage
spec:
  resources:
    requests:
      storage: 12Gi
  accessModes:
    - ReadWriteMany 
  storageClassName: pure-block

