apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pure-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: pure-provisioner
 
parameters:
  backend: block

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-file
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: pure-provisioner
parameters:
  backend: file
